name: Docker Imaging

on:
  push:
    branches:
      - "main"

env:
  TAGS: ${{ github.sha }}
  
  # Please fill this
  DOCKER_REPOSITORY: s3-schedule-backup
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY_ENDPOINT }}

jobs: 
  GoTest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Test
        run: go test -v ./...

  DockerImagingService:
    needs: ["GoTest"]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: DockerHub Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build Docker Image
        run: docker build --tag "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$TAGS" --tag "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest" .

      - name: Dockerhub Push
        run: docker push "$DOCKER_REGISTRY/$DOCKER_REPOSITORY" --all-tags